var municipios = {
    "Aguascalientes":[
            "Aguascalientes",
            "Asientos",
            "Calvillo",
            "Cosío",
            "El Llano",
            "Jesús María",
            "Pabellón De Arteaga",
            "Rincón De Romos",
            "San Francisco De Los Romo",
            "San José De Gracia",
            "Tepezalá"
        ],
    "Baja California":[
            "Ensenada",
            "Mexicali",
            "Playas De Rosarito",
            "Tecate",
            "Tijuana"
        ],
    "Baja California Sur":[
            "Comondú",
            "La Paz",
            "Loreto",
            "Los Cabos",
            "Mulegé"
        ],
    "Campeche":[
            "Calakmul",
            "Calkiní",
            "Campeche",
            "Candelaria",
            "Carmen",
            "Champotón",
            "Escárcega",
            "Hecelchakán",
            "Hopelchén",
            "Palizada",
            "Tenabo"
        ],
    "Coahuila":[
            "Abasolo",
            "Acuña",
            "Allende",
            "Arteaga",
            "Candela",
            "Castaños",
            "Cuatrociénegas",
            "Escobedo",
            "Francisco I. Madero",
            "Frontera",
            "General Cepeda",
            "Guerrero",
            "Hidalgo",
            "Jiménez",
            "Juárez",
            "Lamadrid",
            "Matamoros",
            "Monclova",
            "Morelos",
            "Múzquiz",
            "Nadadores",
            "Nava",
            "Ocampo",
            "Parras",
            "Piedras Negras",
            "Progreso",
            "Ramos Arizpe",
            "Sabinas",
            "Sacramento",
            "Saltillo",
            "San Buenaventura",
            "San Juan De Sabinas",
            "San Pedro",
            "Sierra Mojada",
            "Torreón",
            "Viesca",
            "Villa Unión",
            "Zaragoza"
        ],
    "Colima":[
            "Armería",
            "Colima",
            "Comala",
            "Coquimatlán",
            "Cuauhtémoc",
            "Ixtlahuacán",
            "Manzanillo",
            "Minatitlán",
            "Tecomán",
            "Villa De Alvarez"
        ],
    "Chiapas":[
            "Acacoyagua",
            "Acala",
            "Acapetahua",
            "Aldama",
            "Altamirano",
            "Amatán",
            "Amatenango De La Frontera",
            "Amatenango Del Valle",
            "Angel Albino Corzo",
            "Arriaga",
            "Bejucal De Ocampo",
            "Bella Vista",
            "Benemérito De Las Américas",
            "Berriozábal",
            "Bochil",
            "Cacahoatán",
            "Catazajá",
            "Chalchihuitán",
            "Chamula",
            "Chanal",
            "Chapultenango",
            "Chenalhó",
            "Chiapa De Corzo",
            "Chiapilla",
            "Chicoasén",
            "Chicomuselo",
            "Chilón",
            "Cintalapa",
            "Coapilla",
            "Comitán De Domínguez",
            "Copainalá",
            "El Bosque",
            "El Porvenir",
            "Escuintla",
            "Francisco León",
            "Frontera Comalapa",
            "Frontera Hidalgo",
            "Huehuetán",
            "Huitiupán",
            "Huixtán",
            "Huixtla",
            "Ixhuatán",
            "Ixtacomitán",
            "Ixtapa",
            "Ixtapangajoya",
            "Jiquipilas",
            "Jitotol",
            "Juárez",
            "La Concordia",
            "La Grandeza",
            "La Independencia",
            "La Libertad",
            "La Trinitaria",
            "Larráinzar",
            "Las Margaritas",
            "Las Rosas",
            "Mapastepec",
            "Maravilla Tenejapa",
            "Marqués De Comillas",
            "Mazapa De Madero",
            "Mazatán",
            "Metapa",
            "Mitontic",
            "Montecristo De Guerrero",
            "Motozintla",
            "Nicolás Ruíz",
            "Ocosingo",
            "Ocotepec",
            "Ocozocoautla De Espinosa",
            "Ostuacán",
            "Osumacinta",
            "Oxchuc",
            "Palenque",
            "Pantelhó",
            "Pantepec",
            "Pichucalco",
            "Pijijiapan",
            "Pueblo Nuevo Solistahuacán",
            "Rayón",
            "Reforma",
            "Sabanilla",
            "Salto De Agua",
            "San Andrés Duraznal",
            "San Cristóbal De Las Casas",
            "San Fernando",
            "San Juan Cancuc",
            "San Lucas",
            "Santiago El Pinar",
            "Siltepec",
            "Simojovel",
            "Sitalá",
            "Socoltenango",
            "Solosuchiapa",
            "Soyaló",
            "Suchiapa",
            "Suchiate",
            "Sunuapa",
            "Tapachula",
            "Tapalapa",
            "Tapilula",
            "Tecpatán",
            "Tenejapa",
            "Teopisca",
            "Tila",
            "Tonalá",
            "Totolapa",
            "Tumbalá",
            "Tuxtla Chico",
            "Tuxtla Gutiérrez",
            "Tuzantán",
            "Tzimol",
            "Unión Juárez",
            "Venustiano Carranza",
            "Villa Comaltitlán",
            "Villa Corzo",
            "Villaflores",
            "Yajalón",
            "Zinacantán"
        ],
    "Chihuahua":[
            "Ahumada",
            "Aldama",
            "Allende",
            "Aquiles Serdán",
            "Ascensión",
            "Bachíniva",
            "Balleza",
            "Batopilas",
            "Bocoyna",
            "Buenaventura",
            "Camargo",
            "Carichí",
            "Casas Grandes",
            "Chihuahua",
            "Chínipas",
            "Coronado",
            "Coyame Del Sotol",
            "Cuauhtémoc",
            "Cusihuiriachi",
            "Delicias",
            "Dr. Belisario Domínguez",
            "El Tule",
            "Galeana",
            "Gómez Farías",
            "Gran Morelos",
            "Guachochi",
            "Guadalupe",
            "Guadalupe Y Calvo",
            "Guazapares",
            "Guerrero",
            "Hidalgo Del Parral",
            "Huejotitán",
            "Ignacio Zaragoza",
            "Janos",
            "Jiménez",
            "Juárez",
            "Julimes",
            "La Cruz",
            "López",
            "Madera",
            "Maguarichi",
            "Manuel Benavides",
            "Matachí",
            "Matamoros",
            "Meoqui",
            "Morelos",
            "Moris",
            "Namiquipa",
            "Nonoava",
            "Nuevo Casas Grandes",
            "Ocampo",
            "Ojinaga",
            "Praxedis G. Guerrero",
            "Riva Palacio",
            "Rosales",
            "Rosario",
            "San Francisco De Borja",
            "San Francisco De Conchos",
            "San Francisco Del Oro",
            "Santa Bárbara",
            "Santa Isabel",
            "Satevó",
            "Saucillo",
            "Temósachi",
            "Urique",
            "Uruachi",
            "Valle De Zaragoza"
        ],
    "Distrito Federal":[
            "Alvaro Obregón",
            "Azcapotzalco",
            "Benito Juárez",
            "Coyoacán",
            "Cuajimalpa De Morelos",
            "Cuauhtémoc",
            "Gustavo A. Madero",
            "Iztacalco",
            "Iztapalapa",
            "La Magdalena Contreras",
            "Miguel Hidalgo",
            "Milpa Alta",
            "Tláhuac",
            "Tlalpan",
            "Venustiano Carranza",
            "Xochimilco"
        ],
    "Durango":[
            "Canatlán",
            "Canelas",
            "Coneto De Comonfort",
            "Cuencamé",
            "Durango",
            "El Oro",
            "Gómez Palacio",
            "Gral. Simón Boívar",
            "Guadalupe Victoria",
            "Guanaceví",
            "Hidalgo",
            "Indé",
            "Lerdo",
            "Mapimí",
            "Mezquital",
            "Nazas",
            "Nombre De Dios",
            "Nuevo Ideal",
            "Ocampo",
            "Otáez",
            "Pánuco De Coronado",
            "Peñón Blanco",
            "Poanas",
            "Pueblo Nuevo",
            "Rodeo",
            "San Bernardo",
            "San Dimas",
            "San Juan De Guadalupe",
            "San Juan Del Río",
            "San Luis Del Cordero",
            "San Pedro Del Gallo",
            "Santa Clara",
            "Santiago Papasquiaro",
            "Súchil",
            "Tamazula",
            "Tepehuanes",
            "Tlahualilo",
            "Topia",
            "Vicente Guerrero"
        ],
    "Guanajuato":[
            "Abasolo",
            "Acámbaro",
            "Allende",
            "Apaseo El Alto",
            "Apaseo El Grande",
            "Atarjea",
            "Celaya",
            "Comonfort",
            "Coroneo",
            "Cortazar",
            "Cuerámaro",
            "Doctor Mora",
            "Dolores Hidalgo",
            "Guanajuato",
            "Huanímaro",
            "Irapuato",
            "Jaral Del Progreso",
            "Jerécuaro",
            "León",
            "Manuel Doblado",
            "Moroleón",
            "Ocampo",
            "Pénjamo",
            "Pueblo Nuevo",
            "Purísima Del Rincón",
            "Romita",
            "Salamanca",
            "Salvatierra",
            "San Diego De La Unión",
            "San Felipe",
            "San Francisco Del Rincón",
            "San José Iturbide",
            "San Luis De La Paz",
            "Santa Catarina",
            "Santa Cruz De Juventino Rosas",
            "Santiago Maravatío",
            "Silao",
            "Tarandacuao",
            "Tarimoro",
            "Tierra Blanca",
            "Uriangato",
            "Valle De Santiago",
            "Victoria",
            "Villagrán",
            "Xichú",
            "Yuriria"
        ],
    "Guerrero":[
            "Acapulco De Juárez",
            "Acatepec",
            "Ahuacuotzingo",
            "Ajuchitlán Del Progreso",
            "Alcozauca De Guerrero",
            "Alpoyeca",
            "Apaxtla",
            "Arcelia",
            "Atenango Del Río",
            "Atlamajalcingo Del Monte",
            "Atlixtac",
            "Atoyac De Alvarez",
            "Ayutla De Los Libres",
            "Azoyú",
            "Benito Juárez",
            "Buenavista De Cuéllar",
            "Chilapa De Alvarez",
            "Chilpancingo De Los Bravo",
            "Coahuayutla De José María Izazaga",
            "Cochoapa El Grande",
            "Cocula",
            "Copala",
            "Copalillo",
            "Copanatoyac",
            "Coyuca De Benítez",
            "Coyuca De Catalán",
            "Cuajinicuilapa",
            "Cualác",
            "Cuautepec",
            "Cuetzala Del Progreso",
            "Cutzamala De Pinzón",
            "Eduardo Neri",
            "Florencio Villarreal",
            "General Canuto A. Neri",
            "General Heliodoro Castillo",
            "Huamuxtitlán",
            "Huitzuco De Los Figueroa",
            "Iguala De La Independencia",
            "Igualapa",
            "Ixcateopan De Cuauhtémoc",
            "José Azueta",
            "José Joaquin De Herrera",
            "Juan R. Escudero",
            "La Unión De Isidoro Montes De Oca",
            "Leonardo Bravo",
            "Malinaltepec",
            "Marquelia",
            "Mártir De Cuilapan",
            "Metlatónoc",
            "Mochitlán",
            "Olinalá",
            "Ometepec",
            "Pedro Ascencio Alquisiras",
            "Petatlán",
            "Pilcaya",
            "Pungarabato",
            "Quechultenango",
            "San Luis Acatlán",
            "San Marcos",
            "San Miguel Totolapan",
            "Taxco De Alarcón",
            "Tecoanapa",
            "Técpan De Galeana",
            "Teloloapan",
            "Tepecoacuilco De Trujano",
            "Tetipac",
            "Tixtla De Guerrero",
            "Tlacoachistlahuaca",
            "Tlacoapa",
            "Tlalchapa",
            "Tlalixtaquilla De Maldonado",
            "Tlapa De Comonfort",
            "Tlapehuala",
            "Xalpatláhuac",
            "Xochihuehuetlán",
            "Xochistlahuaca",
            "Zapotitlán Tablas",
            "Zirándaro",
            "Zitlala"
        ],
    "Hidalgo":[
            "Acatlán",
            "Acaxochitlán",
            "Actopan",
            "Agua Blanca De Iturbide",
            "Ajacuba",
            "Alfajayucan",
            "Almoloya",
            "Apan",
            "Atitalaquia",
            "Atlapexco",
            "Atotonilco De Tula",
            "Atotonilco El Grande",
            "Calnali",
            "Cardonal",
            "Chapantongo",
            "Chapulhuacán",
            "Chilcuautla",
            "Cuautepec De Hinojosa",
            "El Arenal",
            "Eloxochitlán",
            "Emiliano Zapata",
            "Epazoyucan",
            "Francisco I. Madero",
            "Huasca De Ocampo",
            "Huautla",
            "Huazalingo",
            "Huehuetla",
            "Huejutla De Reyes",
            "Huichapan",
            "Ixmiquilpan",
            "Jacala De Ledezma",
            "Jaltocán",
            "Juárez Hidalgo",
            "La Misión",
            "Lolotla",
            "Metepec",
            "Metztitlán",
            "Mineral De La Reforma",
            "Mineral Del Chico",
            "Mineral Del Monte",
            "Mixquiahuala De Juárez",
            "Molango De Escamilla",
            "Nicolás Flores",
            "Nopala De Villagrán",
            "Omitlán De Juárez",
            "Pachuca De Soto",
            "Pacula",
            "Pisaflores",
            "Progreso De Obregón",
            "San Agustín Metzquititlán",
            "San Agustín Tlaxiaca",
            "San Bartolo Tutotepec",
            "San Felipe Orizatlán",
            "San Salvador",
            "Santiago De Anaya",
            "Santiago Tulantepec De Lugo Guerre",
            "Singuilucan",
            "Tasquillo",
            "Tecozautla",
            "Tenango De Doria",
            "Tepeapulco",
            "Tepehuacán De Guerrero",
            "Tepeji Del Río De Ocampo",
            "Tepetitlán",
            "Tetepango",
            "Tezontepec De Aldama",
            "Tianguistengo",
            "Tizayuca",
            "Tlahuelilpan",
            "Tlahuiltepa",
            "Tlanalapa",
            "Tlanchinol",
            "Tlaxcoapan",
            "Tolcayuca",
            "Tula De Allende",
            "Tulancingo De Bravo",
            "Villa De Tezontepec",
            "Xochiatipan",
            "Xochicoatlán",
            "Yahualica",
            "Zacualtipán De Ángeles",
            "Zapotlán De Juárez",
            "Zempoala",
            "Zimapán"
        ],
    "Jalisco":[
            "Acatic",
            "Acatlán De Juárez",
            "Ahualulco De Mercado",
            "Amacueca",
            "Amatitán",
            "Ameca",
            "Arandas",
            "Atemajac De Brizuela",
            "Atengo",
            "Atenguillo",
            "Atotonilco El Alto",
            "Atoyac",
            "Autlán De Navarro",
            "Ayotlán",
            "Ayutla",
            "Bolaños",
            "Cabo Corrientes",
            "Cañadas De Obregón",
            "Casimiro Castillo",
            "Chapala",
            "Chimaltitán",
            "Chiquilistlán",
            "Cihuatlán",
            "Cocula",
            "Colotlán",
            "Concepción De Buenos Aires",
            "Cuautitlán De García Barragán",
            "Cuautla",
            "Cuquío",
            "Degollado",
            "Ejutla",
            "El Arenal",
            "El Grullo",
            "El Limón",
            "El Salto",
            "Encarnación De Díaz",
            "Etzatlán",
            "Gómez Farías",
            "Guachinango",
            "Guadalajara",
            "Hostotipaquillo",
            "Huejúcar",
            "Huejuquilla El Alto",
            "Ixtlahuacán De Los Membrillos",
            "Ixtlahuacán Del Río",
            "Jalostotitlán",
            "Jamay",
            "Jesús María",
            "Jilotlán De Los Dolores",
            "Jocotepec",
            "Juanacatlán",
            "Juchitlán",
            "La Barca",
            "La Huerta",
            "La Manzanilla De La Paz",
            "Lagos De Moreno",
            "Magdalena",
            "Mascota",
            "Mazamitla",
            "Mexticacán",
            "Mezquitic",
            "Mixtlán",
            "Ocotlán",
            "Ojuelos De Jalisco",
            "Pihuamo",
            "Poncitlán",
            "Puerto Vallarta",
            "Quitupan",
            "San Cristóbal De La Barranca",
            "San Diego De Alejandría",
            "San Gabriel",
            "San Juan De Los Lagos",
            "San Juanito De Escobedo",
            "San Julián",
            "San Marcos",
            "San Martín De Bolaños",
            "San Martín Hidalgo",
            "San Miguel El Alto",
            "San Sebastián Del Oeste",
            "Santa María De Los ?Ngeles",
            "Santa María Del Oro",
            "Sayula",
            "Tala",
            "Talpa De Allende",
            "Tamazula De Gordiano",
            "Tapalpa",
            "Tecalitlán",
            "Techaluta De Montenegro",
            "Tecolotlán",
            "Tenamaxtlán",
            "Teocaltiche",
            "Teocuitatlán De Corona",
            "Tepatitlán De Morelos",
            "Tequila",
            "Teuchitlán",
            "Tizapán El Alto",
            "Tlajomulco De Zúñiga",
            "Tlaquepaque",
            "Tolimán",
            "Tomatlán",
            "Tonalá",
            "Tonaya",
            "Tonila",
            "Totatiche",
            "Tototlán",
            "Tuxcacuesco",
            "Tuxcueca",
            "Tuxpan",
            "Unión De San Antonio",
            "Unión De Tula",
            "Valle De Guadalupe",
            "Valle De Juárez",
            "Villa Corona",
            "Villa Guerrero",
            "Villa Hidalgo",
            "Villa Purificación",
            "Yahualica De González Gallo",
            "Zacoalco De Torres",
            "Zapopan",
            "Zapotiltic",
            "Zapotitlán De Vadillo",
            "Zapotlán Del Rey",
            "Zapotlán El Grande",
            "Zapotlanejo"
        ],
    "Estado De Mexico":[
            "Acambay",
            "Acolman",
            "Aculco",
            "Almoloya De Alquisiras",
            "Almoloya De Juárez",
            "Almoloya Del Río",
            "Amanalco",
            "Amatepec",
            "Amecameca",
            "Apaxco",
            "Atenco",
            "Atizapán",
            "Atizapán De Zaragoza",
            "Atlacomulco",
            "Atlautla",
            "Axapusco",
            "Ayapango",
            "Calimaya",
            "Capulhuac",
            "Chalco",
            "Chapa De Mota",
            "Chapultepec",
            "Chiautla",
            "Chicoloapan",
            "Chiconcuac",
            "Chimalhuacán",
            "Coacalco De Berriozábal",
            "Coatepec Harinas",
            "Cocotitlán",
            "Coyotepec",
            "Cuautitlán",
            "Cuautitlán Izcalli",
            "Donato Guerra",
            "Ecatepec De Morelos",
            "Ecatzingo",
            "El Oro",
            "Huehuetoca",
            "Hueypoxtla",
            "Huixquilucan",
            "Isidro Fabela",
            "Ixtapaluca",
            "Ixtapan De La Sal",
            "Ixtapan Del Oro",
            "Ixtlahuaca",
            "Jaltenco",
            "Jilotepec",
            "Jilotzingo",
            "Jiquipilco",
            "Jocotitlán",
            "Joquicingo",
            "Juchitepec",
            "La Paz",
            "Lerma",
            "Luvianos",
            "Malinalco",
            "Melchor Ocampo",
            "Metepec",
            "Mexicaltzingo",
            "Morelos",
            "Naucalpan De Juárez",
            "Nextlalpan",
            "Nezahualcóyotl",
            "Nicolás Romero",
            "Nopaltepec",
            "Ocoyoacac",
            "Ocuilan",
            "Otumba",
            "Otzoloapan",
            "Otzolotepec",
            "Ozumba",
            "Papalotla",
            "Polotitlán",
            "Rayón",
            "San Antonio La Isla",
            "San Felipe Del Progreso",
            "San José Del Rincón",
            "San Martín De Las Pirámides",
            "San Mateo Atenco",
            "San Simón De Guerrero",
            "Santo Tomás",
            "Soyaniquilpan De Juárez",
            "Sultepec",
            "Tecámac",
            "Tejupilco",
            "Temamatla",
            "Temascalapa",
            "Temascalcingo",
            "Temascaltepec",
            "Temoaya",
            "Tenancingo",
            "Tenango Del Aire",
            "Tenango Del Valle",
            "Teoloyucán",
            "Teotihuacán",
            "Tepetlaoxtoc",
            "Tepetlixpa",
            "Tepotzotlán",
            "Tequixquiac",
            "Texcaltitlán",
            "Texcalyacac",
            "Texcoco",
            "Tezoyuca",
            "Tianguistenco",
            "Timilpan",
            "Tlalmanalco",
            "Tlalnepantla De Baz",
            "Tlatlaya",
            "Toluca",
            "Tonanitla",
            "Tonatico",
            "Tultepec",
            "Tultitlán",
            "Valle De Bravo",
            "Valle De Chalco Solidaridad",
            "Villa De Allende",
            "Villa Del Carbón",
            "Villa Guerrero",
            "Villa Victoria",
            "Xalatlaco",
            "Xonacatlán",
            "Zacazonapan",
            "Zacualpan",
            "Zinacantepec",
            "Zumpahuacán",
            "Zumpango"
        ],
    "Michoacan":[
            "Acuitzio",
            "Aguililla",
            "Alvaro Obregón",
            "Angamacutiro",
            "Angangueo",
            "Apatzingán",
            "Aporo",
            "Aquila",
            "Ario",
            "Arteaga",
            "Briseñas",
            "Buenavista",
            "Carácuaro",
            "Charapan",
            "Charo",
            "Chavinda",
            "Cherán",
            "Chilchota",
            "Chinicuila",
            "Chucándiro",
            "Churintzio",
            "Churumuco",
            "Coahuayana",
            "Coalcomán De Vázquez Pallares",
            "Coeneo",
            "Cojumatlán De Régules",
            "Contepec",
            "Copándaro",
            "Cotija",
            "Cuitzeo",
            "Ecuandureo",
            "Epitacio Huerta",
            "Erongarícuaro",
            "Gabriel Zamora",
            "Hidalgo",
            "Huandacareo",
            "Huaniqueo",
            "Huetamo",
            "Huiramba",
            "Indaparapeo",
            "Irimbo",
            "Ixtlán",
            "Jacona",
            "Jiménez",
            "Jiquilpan",
            "José Sixto Verduzco",
            "Juárez",
            "Jungapeo",
            "La Huacana",
            "La Piedad",
            "Lagunillas",
            "Lázaro Cárdenas",
            "Los Reyes",
            "Madero",
            "Maravatío",
            "Marcos Castellanos",
            "Morelia",
            "Morelos",
            "Múgica",
            "Nahuatzen",
            "Nocupétaro",
            "Nuevo Parangaricutiro",
            "Nuevo Urecho",
            "Numarán",
            "Ocampo",
            "Pajacuarán",
            "Panindícuaro",
            "Paracho",
            "Parácuaro",
            "Pátzcuaro",
            "Penjamillo",
            "Peribán",
            "Purépero",
            "Puruándiro",
            "Queréndaro",
            "Quiroga",
            "Sahuayo",
            "Salvador Escalante",
            "San Lucas",
            "Santa Ana Maya",
            "Senguio",
            "Susupuato",
            "Tacámbaro",
            "Tancítaro",
            "Tangamandapio",
            "Tangancícuaro",
            "Tanhuato",
            "Taretan",
            "Tarímbaro",
            "Tepalcatepec",
            "Ting?Indín",
            "Tingambato",
            "Tiquicheo De Nicolás Romero",
            "Tlalpujahua",
            "Tlazazalca",
            "Tocumbo",
            "Tumbiscatío",
            "Turicato",
            "Tuxpan",
            "Tuzantla",
            "Tzintzuntzan",
            "Tzitzio",
            "Uruapan",
            "Venustiano Carranza",
            "Villamar",
            "Vista Hermosa",
            "Yurécuaro",
            "Zacapu",
            "Zamora",
            "Zináparo",
            "Zinapécuaro",
            "Ziracuaretiro",
            "Zitácuaro"
        ],
    "Morelos":[
            "Amacuzac",
            "Atlatlahucan",
            "Axochiapan",
            "Ayala",
            "Coatlán Del Río",
            "Cuautla",
            "Cuernavaca",
            "Emiliano Zapata",
            "Huitzilac",
            "Jantetelco",
            "Jiutepec",
            "Jojutla",
            "Jonacatepec",
            "Mazatepec",
            "Miacatlán",
            "Ocuituco",
            "Puente De Ixtla",
            "Temixco",
            "Temoac",
            "Tepalcingo",
            "Tepoztlán",
            "Tetecala",
            "Tetela Del Volcán",
            "Tlalnepantla",
            "Tlaltizapán",
            "Tlaquiltenango",
            "Tlayacapan",
            "Totolapan",
            "Xochitepec",
            "Yautepec",
            "Yecapixtla",
            "Zacatepec De Hidalgo",
            "Zacualpan De Amilpas"
        ],
    "Nayarit":[
            "Acaponeta",
            "Ahuacatlán",
            "Amatlán De Cañas",
            "Bahía De Banderas",
            "Compostela",
            "Del Nayar",
            "Huajicori",
            "Ixtlán Del Río",
            "Jala",
            "La Yesca",
            "Rosamorada",
            "Ruíz",
            "San Blas",
            "San Pedro Lagunillas",
            "Santa María Del Oro",
            "Santiago Ixcuintla",
            "Tecuala",
            "Tepic",
            "Tuxpan",
            "Xalisco"
        ],
    "Nuevo Leon":[
            "Abasolo",
            "Agualeguas",
            "Allende",
            "Anáhuac",
            "Apodaca",
            "Aramberri",
            "Bustamante",
            "Cadereyta Jiménez",
            "Carmen",
            "Cerralvo",
            "China",
            "Ciénega De Flores",
            "Dr. Coss",
            "Dr. Arroyo",
            "Dr. González",
            "Galeana",
            "García",
            "Gral. Escobedo",
            "Gral. Terán",
            "Gral. Treviño",
            "Gral. Zaragoza",
            "Gral. Zuazua",
            "Gral. Bravo",
            "Guadalupe",
            "Hidalgo",
            "Higueras",
            "Hualahuises",
            "Iturbide",
            "Juárez",
            "Lampazos De Naranjo",
            "Linares",
            "Los Aldamas",
            "Los Herreras",
            "Los Ramones",
            "Marín",
            "Melchor Ocampo",
            "Mier Y Noriega",
            "Mina",
            "Montemorelos",
            "Monterrey",
            "Parás",
            "Pesquería",
            "Rayones",
            "Sabinas Hidalgo",
            "Salinas Victoria",
            "San Nicolás De Los Garza",
            "San Pedro Garza García",
            "Santa Catarina",
            "Santiago",
            "Vallecillo",
            "Villaldama"
        ],
    "Oaxaca":[
            "Abejones",
            "Acatlán De Pérez Figueroa",
            "Animas Trujano",
            "Asunción Cacalotepec",
            "Asunción Cuyotepeji",
            "Asunción Ixtaltepec",
            "Asunción Nochixtlán",
            "Asunción Ocotlán",
            "Asunción Tlacolulita",
            "Ayoquezco De Aldama",
            "Ayotzintepec",
            "Calihualá",
            "Candelaria Loxicha",
            "Capulálpam De Méndez",
            "Chahuites",
            "Chalcatongo De Hidalgo",
            "Chiquihuitlán De Benito Juárez",
            "Ciénega De Zimatlán",
            "Ciudad Ixtepec",
            "Coatecas Altas",
            "Coicoyán De Las Flores",
            "Concepción Buenavista",
            "Concepción Pápalo",
            "Constancia Del Rosario",
            "Cosolapa",
            "Cosoltepec",
            "Cuilápam De Guerrero",
            "Cuyamecalco Villa De Zaragoza",
            "El Barrio De La Soledad",
            "El Espinal",
            "Eloxochitlán De Flores Magón",
            "Fresnillo De Trujano",
            "Guadalupe De Ramírez",
            "Guadalupe Etla",
            "Guelatao De Juárez",
            "Guevea De Humboldt",
            "Heroica Ciudad De Ejutla De Crespo",
            "Heroica Ciudad De Huajuapan De Leó",
            "Heroica Ciudad De Tlaxiaco",
            "Huautepec",
            "Huautla De Jiménez",
            "Ixpantepec Nieves",
            "Ixtlán De Juárez",
            "Juchitán De Zaragoza",
            "La Compañía",
            "La Pe",
            "La Reforma",
            "La Trinidad Vista Hermosa",
            "Loma Bonita",
            "Magdalena Apasco",
            "Magdalena Jaltepec",
            "Magdalena Mixtepec",
            "Magdalena Ocotlán",
            "Magdalena Peñasco",
            "Magdalena Teitipac",
            "Magdalena Tequisistlán",
            "Magdalena Tlacotepec",
            "Magdalena Yodocono De Porfirio Día",
            "Magdalena Zahuatlán",
            "Mariscala De Juárez",
            "Mártires De Tacubaya",
            "Matías Romero Avendaño",
            "Mazatlán Villa De Flores",
            "Mesones Hidalgo",
            "Miahuatlán De Porfirio Díaz",
            "Mixistlán De La Reforma",
            "Monjas",
            "Natividad",
            "Nazareno Etla",
            "Nejapa De Madero",
            "Nuevo Zoquiapam",
            "Oaxaca De Juárez",
            "Ocotlán De Morelos",
            "Pinotepa De Don Luis",
            "Pluma Hidalgo",
            "Putla Villa De Guerrero",
            "Reforma De Pineda",
            "Reyes Etla",
            "Rojas De Cuauhtémoc",
            "Salina Cruz",
            "San Agustín Amatengo",
            "San Agustín Atenango",
            "San Agustín Chayuco",
            "San Agustín De Las Juntas",
            "San Agustín Etla",
            "San Agustín Loxicha",
            "San Agustín Tlacotepec",
            "San Agustín Yatareni",
            "San Andrés Cabecera Nueva",
            "San Andrés Dinicuiti",
            "San Andrés Huaxpaltepec",
            "San Andrés Huayapam",
            "San Andrés Ixtlahuaca",
            "San Andrés Lagunas",
            "San Andrés Nuxiño",
            "San Andrés Paxtlán",
            "San Andrés Sinaxtla",
            "San Andrés Solaga",
            "San Andrés Teotilalpam",
            "San Andrés Tepetlapa",
            "San Andrés Yaá",
            "San Andrés Zabache",
            "San Andrés Zautla",
            "San Antonino Castillo Velasco",
            "San Antonino El Alto",
            "San Antonino Monte Verde",
            "San Antonio Acutla",
            "San Antonio De La Cal",
            "San Antonio Huitepec",
            "San Antonio Nanahuatípam",
            "San Antonio Sinicahua",
            "San Antonio Tepetlapa",
            "San Baltazar Chichicápam",
            "San Baltazar Loxicha",
            "San Baltazar Yatzachi El Bajo",
            "San Bartolo Coyotepec",
            "San Bartolo Soyaltepec",
            "San Bartolo Yautepec",
            "San Bartolomé Ayautla",
            "San Bartolomé Loxicha",
            "San Bartolomé Quialana",
            "San Bartolomé Yucuañe",
            "San Bartolomé Zoogocho",
            "San Bernardo Mixtepec",
            "San Blas Atempa",
            "San Carlos Yautepec",
            "San Cristóbal Amatlán",
            "San Cristóbal Amoltepec",
            "San Cristóbal Lachirioag",
            "San Cristóbal Suchixtlahuaca",
            "San Dionisio Del Mar",
            "San Dionisio Ocotepec",
            "San Dionisio Ocotlán",
            "San Esteban Atatlahuca",
            "San Felipe Jalapa De Díaz",
            "San Felipe Tejalapam",
            "San Felipe Usila",
            "San Francisco Cahuacuá",
            "San Francisco Cajonos",
            "San Francisco Chapulapa",
            "San Francisco Chindúa",
            "San Francisco Del Mar",
            "San Francisco Huehuetlán",
            "San Francisco Ixhuatán",
            "San Francisco Jaltepetongo",
            "San Francisco Lachigoló",
            "San Francisco Logueche",
            "San Francisco Nuxaño",
            "San Francisco Ozolotepec",
            "San Francisco Sola",
            "San Francisco Telixtlahuaca",
            "San Francisco Teopan",
            "San Francisco Tlapancingo",
            "San Gabriel Mixtepec",
            "San Ildefonso Amatlán",
            "San Ildefonso Sola",
            "San Ildefonso Villa Alta",
            "San Jacinto Amilpas",
            "San Jacinto Tlacotepec",
            "San Jerónimo Coatlán",
            "San Jerónimo Silacayoapilla",
            "San Jerónimo Sosola",
            "San Jerónimo Taviche",
            "San Jerónimo Tecoátl",
            "San Jerónimo Tlacochahuaya",
            "San Jorge Nuchita",
            "San José Ayuquila",
            "San José Chiltepec",
            "San José Del Peñasco",
            "San José Del Progreso",
            "San José Estancia Grande",
            "San José Independencia",
            "San José Lachiguiri",
            "San José Tenango",
            "San Juan ?Umí",
            "San Juan Achiutla",
            "San Juan Atepec",
            "San Juan Bautista Atatlahuca",
            "San Juan Bautista Coixtlahuaca",
            "San Juan Bautista Cuicatlán",
            "San Juan Bautista Guelache",
            "San Juan Bautista Jayacatlán",
            "San Juan Bautista Lo De Soto",
            "San Juan Bautista Suchitepec",
            "San Juan Bautista Tlachichilco",
            "San Juan Bautista Tlacoatzintepec",
            "San Juan Bautista Tuxtepec",
            "San Juan Bautista Valle Nacional",
            "San Juan Cacahuatepec",
            "San Juan Chicomezúchil",
            "San Juan Chilateca",
            "San Juan Cieneguilla",
            "San Juan Coatzóspam",
            "San Juan Colorado",
            "San Juan Comaltepec",
            "San Juan Cotzocón",
            "San Juan De Los Cués",
            "San Juan Del Estado",
            "San Juan Del Río",
            "San Juan Diuxi",
            "San Juan Evangelista Analco",
            "San Juan Guelavía",
            "San Juan Guichicovi",
            "San Juan Ihualtepec",
            "San Juan Juquila Mixes",
            "San Juan Juquila Vijanos",
            "San Juan Lachao",
            "San Juan Lachigalla",
            "San Juan Lajarcia",
            "San Juan Lalana",
            "San Juan Mazatlán",
            "San Juan Mixtepec",
            "San Juan Mixtepec",
            "San Juan Ozolotepec",
            "San Juan Petlapa",
            "San Juan Quiahije",
            "San Juan Quiotepec",
            "San Juan Sayultepec",
            "San Juan Tabaá",
            "San Juan Tamazola",
            "San Juan Teita",
            "San Juan Teitipac",
            "San Juan Tepeuxila",
            "San Juan Teposcolula",
            "San Juan Yaeé",
            "San Juan Yatzona",
            "San Juan Yucuita",
            "San Lorenzo",
            "San Lorenzo Albarradas",
            "San Lorenzo Cacaotepec",
            "San Lorenzo Cuaunecuiltitla",
            "San Lorenzo Texmelucan",
            "San Lorenzo Victoria",
            "San Lucas Camotlán",
            "San Lucas Ojitlán",
            "San Lucas Quiaviní",
            "San Lucas Zoquiápam",
            "San Luis Amatlán",
            "San Marcial Ozolotepec",
            "San Marcos Arteaga",
            "San Martín De Los Cansecos",
            "San Martín Huamelúlpam",
            "San Martín Itunyoso",
            "San Martín Lachilá",
            "San Martín Peras",
            "San Martín Tilcajete",
            "San Martín Toxpalan",
            "San Martín Zacatepec",
            "San Mateo Cajonos",
            "San Mateo Del Mar",
            "San Mateo Etlatongo",
            "San Mateo Nejápam",
            "San Mateo Peñasco",
            "San Mateo Piñas",
            "San Mateo Río Hondo",
            "San Mateo Sindihui",
            "San Mateo Tlapiltepec",
            "San Mateo Yoloxochitlán",
            "San Melchor Betaza",
            "San Miguel Achiutla",
            "San Miguel Ahuehuetitlán",
            "San Miguel Aloápam",
            "San Miguel Amatitlán",
            "San Miguel Amatlán",
            "San Miguel Chicahua",
            "San Miguel Chimalapa",
            "San Miguel Coatlán",
            "San Miguel Del Puerto",
            "San Miguel Del Río",
            "San Miguel Ejutla",
            "San Miguel El Grande",
            "San Miguel Huautla",
            "San Miguel Mixtepec",
            "San Miguel Panixtlahuaca",
            "San Miguel Peras",
            "San Miguel Piedras",
            "San Miguel Quetzaltepec",
            "San Miguel Santa Flor",
            "San Miguel Soyaltepec",
            "San Miguel Suchixtepec",
            "San Miguel Tecomatlán",
            "San Miguel Tenango",
            "San Miguel Tequixtepec",
            "San Miguel Tilquiápam",
            "San Miguel Tlacamama",
            "San Miguel Tlacotepec",
            "San Miguel Tulancingo",
            "San Miguel Yotao",
            "San Nicolás",
            "San Nicolás Hidalgo",
            "San Pablo Coatlán",
            "San Pablo Cuatro Venados",
            "San Pablo Etla",
            "San Pablo Huitzo",
            "San Pablo Huixtepec",
            "San Pablo Macuiltianguis",
            "San Pablo Tijaltepec",
            "San Pablo Villa De Mitla",
            "San Pablo Yaganiza",
            "San Pedro Amuzgos",
            "San Pedro Apóstol",
            "San Pedro Atoyac",
            "San Pedro Cajonos",
            "San Pedro Comitancillo",
            "San Pedro Coxcaltepec Cántaros",
            "San Pedro El Alto",
            "San Pedro Huamelula",
            "San Pedro Huilotepec",
            "San Pedro Ixcatlán",
            "San Pedro Ixtlahuaca",
            "San Pedro Jaltepetongo",
            "San Pedro Jicayán",
            "San Pedro Jocotipac",
            "San Pedro Juchatengo",
            "San Pedro Mártir",
            "San Pedro Mártir Quiechapa",
            "San Pedro Mártir Yucuxaco",
            "San Pedro Mixtepec",
            "San Pedro Mixtepec",
            "San Pedro Molinos",
            "San Pedro Nopala",
            "San Pedro Ocopetatillo",
            "San Pedro Ocotepec",
            "San Pedro Pochutla",
            "San Pedro Quiatoni",
            "San Pedro Sochiapam",
            "San Pedro Tapanatepec",
            "San Pedro Taviche",
            "San Pedro Teozacoalco",
            "San Pedro Teutila",
            "San Pedro Tidaá",
            "San Pedro Topiltepec",
            "San Pedro Totolapa",
            "San Pedro Y San Pablo Ayutla",
            "San Pedro Y San Pablo Teposcolula",
            "San Pedro Y San Pablo Tequixtepec",
            "San Pedro Yaneri",
            "San Pedro Yólox",
            "San Pedro Yucunama",
            "San Raymundo Jalpan",
            "San Sebastián Abasolo",
            "San Sebastián Coatlán",
            "San Sebastián Ixcapa",
            "San Sebastián Nicananduta",
            "San Sebastián Río Hondo",
            "San Sebastián Tecomaxtlahuaca",
            "San Sebastián Teitipac",
            "San Sebastián Tutla",
            "San Simón Almolongas",
            "San Simón Zahuatlán",
            "San Vicente Coatlán",
            "San Vicente Lachixío",
            "San Vicente Nuñú",
            "Santa Ana",
            "Santa Ana Ateixtlahuaca",
            "Santa Ana Cuauhtémoc",
            "Santa Ana Del Valle",
            "Santa Ana Tavela",
            "Santa Ana Tlapacoyan",
            "Santa Ana Yareni",
            "Santa Ana Zegache",
            "Santa Catalina Quierí",
            "Santa Catarina Cuixtla",
            "Santa Catarina Ixtepeji",
            "Santa Catarina Juquila",
            "Santa Catarina Lachatao",
            "Santa Catarina Loxicha",
            "Santa Catarina Mechoacán",
            "Santa Catarina Minas",
            "Santa Catarina Quiané",
            "Santa Catarina Quioquitani",
            "Santa Catarina Tayata",
            "Santa Catarina Ticuá",
            "Santa Catarina Yosonotú",
            "Santa Catarina Zapoquila",
            "Santa Cruz Acatepec",
            "Santa Cruz Amilpas",
            "Santa Cruz De Bravo",
            "Santa Cruz Itundujia",
            "Santa Cruz Mixtepec",
            "Santa Cruz Nundaco",
            "Santa Cruz Papalutla",
            "Santa Cruz Tacache De Mina",
            "Santa Cruz Tacahua",
            "Santa Cruz Tayata",
            "Santa Cruz Xitla",
            "Santa Cruz Xoxocotlán",
            "Santa Cruz Zenzontepec",
            "Santa Gertrudis",
            "Santa Inés De Zaragoza",
            "Santa Inés Del Monte",
            "Santa Inés Yatzeche",
            "Santa Lucía Del Camino",
            "Santa Lucía Miahuatlán",
            "Santa Lucía Monteverde",
            "Santa Lucía Ocotlán",
            "Santa Magdalena Jicotlán",
            "Santa María Alotepec",
            "Santa María Apazco",
            "Santa María Atzompa",
            "Santa María Camotlán",
            "Santa María Chachoápam",
            "Santa María Chilchotla",
            "Santa María Chimalapa",
            "Santa María Colotepec",
            "Santa María Cortijo",
            "Santa María Coyotepec",
            "Santa María Del Rosario",
            "Santa María Del Tule",
            "Santa María Ecatepec",
            "Santa María Guelacé",
            "Santa María Guienagati",
            "Santa María Huatulco",
            "Santa María Huazolotitlán",
            "Santa María Ipalapa",
            "Santa María Ixcatlán",
            "Santa María Jacatepec",
            "Santa María Jalapa Del Marqués",
            "Santa María Jaltianguis",
            "Santa María La Asunción",
            "Santa María Lachixío",
            "Santa María Mixtequilla",
            "Santa María Nativitas",
            "Santa María Nduayaco",
            "Santa María Ozolotepec",
            "Santa María Pápalo",
            "Santa María Peñoles",
            "Santa María Petapa",
            "Santa María Quiegolani",
            "Santa María Sola",
            "Santa María Tataltepec",
            "Santa María Tecomavaca",
            "Santa María Temaxcalapa",
            "Santa María Temaxcaltepec",
            "Santa María Teopoxco",
            "Santa María Tepantlali",
            "Santa María Texcatitlán",
            "Santa María Tlahuitoltepec",
            "Santa María Tlalixtac",
            "Santa María Tonameca",
            "Santa María Totolapilla",
            "Santa María Xadani",
            "Santa María Yalina",
            "Santa María Yavesía",
            "Santa María Yolotepec",
            "Santa María Yosoyúa",
            "Santa María Yucuhiti",
            "Santa María Zacatepec",
            "Santa María Zaniza",
            "Santa María Zoquitlán",
            "Santiago Amoltepec",
            "Santiago Apoala",
            "Santiago Apóstol",
            "Santiago Astata",
            "Santiago Atitlán",
            "Santiago Ayuquililla",
            "Santiago Cacaloxtepec",
            "Santiago Camotlán",
            "Santiago Chazumba",
            "Santiago Choapam",
            "Santiago Comaltepec",
            "Santiago Del Río",
            "Santiago Huajolotitlán",
            "Santiago Huauclilla",
            "Santiago Ihuitlán Plumas",
            "Santiago Ixcuintepec",
            "Santiago Ixtayutla",
            "Santiago Jamiltepec",
            "Santiago Jocotepec",
            "Santiago Juxtlahuaca",
            "Santiago Lachiguiri",
            "Santiago Lalopa",
            "Santiago Laollaga",
            "Santiago Laxopa",
            "Santiago Llano Grande",
            "Santiago Matatlán",
            "Santiago Miltepec",
            "Santiago Minas",
            "Santiago Nacaltepec",
            "Santiago Nejapilla",
            "Santiago Niltepec",
            "Santiago Nundiche",
            "Santiago Nuyoó",
            "Santiago Pinotepa Nacional",
            "Santiago Suchilquitongo",
            "Santiago Tamazola",
            "Santiago Tapextla",
            "Santiago Tenango",
            "Santiago Tepetlapa",
            "Santiago Tetepec",
            "Santiago Texcalcingo",
            "Santiago Textitlán",
            "Santiago Tilantongo",
            "Santiago Tillo",
            "Santiago Tlazoyaltepec",
            "Santiago Xanica",
            "Santiago Xiacuí",
            "Santiago Yaitepec",
            "Santiago Yaveo",
            "Santiago Yolomécatl",
            "Santiago Yosondúa",
            "Santiago Yucuyachi",
            "Santiago Zacatepec",
            "Santiago Zoochila",
            "Santo Domingo Albarradas",
            "Santo Domingo Armenta",
            "Santo Domingo Chihuitán",
            "Santo Domingo De Morelos",
            "Santo Domingo Ingenio",
            "Santo Domingo Ixcatlán",
            "Santo Domingo Nuxaá",
            "Santo Domingo Ozolotepec",
            "Santo Domingo Petapa",
            "Santo Domingo Roayaga",
            "Santo Domingo Tehuantepec",
            "Santo Domingo Teojomulco",
            "Santo Domingo Tepuxtepec",
            "Santo Domingo Tlatayápam",
            "Santo Domingo Tomaltepec",
            "Santo Domingo Tonalá",
            "Santo Domingo Tonaltepec",
            "Santo Domingo Xagacía",
            "Santo Domingo Yanhuitlán",
            "Santo Domingo Yodohino",
            "Santo Domingo Zanatepec",
            "Santo Tomás Jalieza",
            "Santo Tomás Mazaltepec",
            "Santo Tomás Ocotepec",
            "Santo Tomás Tamazulapan",
            "Santos Reyes Nopala",
            "Santos Reyes Pápalo",
            "Santos Reyes Tepejillo",
            "Santos Reyes Yucuná",
            "Silacayoápam",
            "Sitio De Xitlapehua",
            "Soledad Etla",
            "Tamazulapam Del Espíritu Santo",
            "Tanetze De Zaragoza",
            "Taniche",
            "Tataltepec De Valdés",
            "Teococuilco De Marcos Pérez",
            "Teotitlán De Flores Magón",
            "Teotitlán Del Valle",
            "Teotongo",
            "Tepelmeme Villa De Morelos",
            "Tezoatlán De Segura Y Luna",
            "Tlacolula De Matamoros",
            "Tlacotepec Plumas",
            "Tlalixtac De Cabrera",
            "Totontepec Villa De Morelos",
            "Trinidad Zaachila",
            "Unión Hidalgo",
            "Valerio Trujano",
            "Villa De Chilapa De Díaz",
            "Villa De Etla",
            "Villa De Tamazulápam Del Progreso",
            "Villa De Tututepec De Melchor Ocam",
            "Villa De Zaachila",
            "Villa Díaz Ordaz",
            "Villa Hidalgo",
            "Villa Sola De Vega",
            "Villa Talea De Castro",
            "Villa Tejúpam De La Unión",
            "Yaxe",
            "Yogana",
            "Yutanduchi De Guerrero",
            "Zapotitlán Del Río",
            "Zapotitlán Lagunas",
            "Zapotitlán Palmas",
            "Zimatlán De Alvarez"
        ],
    "Puebla":[
            "Acajete",
            "Acateno",
            "Acatlán",
            "Acatzingo",
            "Acteopan",
            "Ahuacatlán",
            "Ahuatlán",
            "Ahuazotepec",
            "Ahuehuetitla",
            "Ajalpan",
            "Albino Zertuche",
            "Aljojuca",
            "Altepexi",
            "Amixtlán",
            "Amozoc",
            "Aquixtla",
            "Atempan",
            "Atexcal",
            "Atlequizayan",
            "Atlixco",
            "Atoyatempan",
            "Atzala",
            "Atzitzihuacán",
            "Atzitzintla",
            "Axutla",
            "Ayotoxco De Guerrero",
            "Calpan",
            "Caltepec",
            "Camocuautla",
            "Cañada Morelos",
            "Caxhuacan",
            "Chalchicomula De Sesma",
            "Chapulco",
            "Chiautla",
            "Chiautzingo",
            "Chichiquila",
            "Chiconcuautla",
            "Chietla",
            "Chigmecatitlán",
            "Chignahuapan",
            "Chignautla",
            "Chila",
            "Chila De La Sal",
            "Chilchotla",
            "Chinantla",
            "Coatepec",
            "Coatzingo",
            "Cohetzala",
            "Cohuecán",
            "Coronango",
            "Coxcatlán",
            "Coyomeapan",
            "Coyotepec",
            "Cuapiaxtla De Madero",
            "Cuautempan",
            "Cuautinchán",
            "Cuautlancingo",
            "Cuayuca De Andrade",
            "Cuetzalan Del Progreso",
            "Cuyoaco",
            "Domingo Arenas",
            "Eloxochitlán",
            "Epatlán",
            "Esperanza",
            "Francisco Z. Mena",
            "General Felipe ?Ngeles",
            "Guadalupe",
            "Guadalupe Victoria",
            "Hermenegildo Galeana",
            "Honey",
            "Huaquechula",
            "Huatlatlauca",
            "Huauchinango",
            "Huehuetla",
            "Huehuetlán El Chico",
            "Huehuetlán El Grande",
            "Huejotzingo",
            "Hueyapan",
            "Hueytamalco",
            "Hueytlalpan",
            "Huitzilan De Serdán",
            "Huitziltepec",
            "Ixcamilpa De Guerrero",
            "Ixcaquixtla",
            "Ixtacamaxtitlán",
            "Ixtepec",
            "Izúcar De Matamoros",
            "Jalpan",
            "Jolalpan",
            "Jonotla",
            "Jopala",
            "Juan C. Bonilla",
            "Juan Galindo",
            "Juan N. Méndez",
            "La Magdalena Tlatlauquitepec",
            "Lafragua",
            "Libres",
            "Los Reyes De Juárez",
            "Mazapiltepec De Juárez",
            "Mixtla",
            "Molcaxac",
            "Naupan",
            "Nauzontla",
            "Nealtican",
            "Nicolás Bravo",
            "Nopalucan",
            "Ocotepec",
            "Ocoyucan",
            "Olintla",
            "Oriental",
            "Pahuatlán",
            "Palmar De Bravo",
            "Pantepec",
            "Petlalcingo",
            "Piaxtla",
            "Puebla",
            "Quecholac",
            "Quimixtlán",
            "Rafael Lara Grajales",
            "San Andrés Cholula",
            "San Antonio Cañada",
            "San Diego La Mesa Tochimiltzingo",
            "San Felipe Teotlalcingo",
            "San Felipe Tepatlán",
            "San Gabriel Chilac",
            "San Gregorio Atzompa",
            "San Jerónimo Tecuanipan",
            "San Jerónimo Xayacatlán",
            "San José Chiapa",
            "San José Miahuatlán",
            "San Juan Atenco",
            "San Juan Atzompa",
            "San Martín Texmelucan",
            "San Martín Totoltepec",
            "San Matías Tlalancaleca",
            "San Miguel Ixitlán",
            "San Miguel Xoxtla",
            "San Nicolás Buenos Aires",
            "San Nicolás De Los Ranchos",
            "San Pablo Anicano",
            "San Pedro Cholula",
            "San Pedro Yeloixtlahuaca",
            "San Salvador El Seco",
            "San Salvador El Verde",
            "San Salvador Huixcolotla",
            "San Sebastián Tlacotepec",
            "Santa Catarina Tlaltempan",
            "Santa Inés Ahuatempan",
            "Santa Isabel Cholula",
            "Santiago Miahuatlán",
            "Santo Tomás Hueyotlipan",
            "Soltepec",
            "Tecali De Herrera",
            "Tecamachalco",
            "Tecomatlán",
            "Tehuacán",
            "Tehuitzingo",
            "Tenampulco",
            "Teopantlán",
            "Teotlalco",
            "Tepanco De López",
            "Tepango De Rodríguez",
            "Tepatlaxco De Hidalgo",
            "Tepeaca",
            "Tepemaxalco",
            "Tepeojuma",
            "Tepetzintla",
            "Tepexco",
            "Tepexi De Rodríguez",
            "Tepeyahualco",
            "Tepeyahualco De Cuauhtémoc",
            "Tetela De Ocampo",
            "Teteles De Avila Castillo",
            "Teziutlán",
            "Tianguismanalco",
            "Tilapa",
            "Tlachichuca",
            "Tlacotepec De Benito Juárez",
            "Tlacuilotepec",
            "Tlahuapan",
            "Tlaltenango",
            "Tlanepantla",
            "Tlaola",
            "Tlapacoya",
            "Tlapanalá",
            "Tlatlauquitepec",
            "Tlaxco",
            "Tochimilco",
            "Tochtepec",
            "Totoltepec De Guerrero",
            "Tulcingo",
            "Tuzamapan De Galeana",
            "Tzicatlacoyan",
            "Venustiano Carranza",
            "Vicente Guerrero",
            "Xayacatlán De Bravo",
            "Xicotepec",
            "Xicotlán",
            "Xiutetelco",
            "Xochiapulco",
            "Xochiltepec",
            "Xochitlán De Vicente Suárez",
            "Xochitlán Todos Santos",
            "Yaonáhuac",
            "Yehualtepec",
            "Zacapala",
            "Zacapoaxtla",
            "Zacatlán",
            "Zapotitlán",
            "Zapotitlán De Méndez",
            "Zaragoza",
            "Zautla",
            "Zihuateutla",
            "Zinacatepec",
            "Zongozotla",
            "Zoquiapan",
            "Zoquitlán"
        ],
    "Queretaro":[
            "Amealco De Bonfil",
            "Arroyo Seco",
            "Cadereyta De Montes",
            "Colón",
            "Corregidora",
            "El Marqués",
            "Ezequiel Montes",
            "Huimilpan",
            "Jalpan De Serra",
            "Landa De Matamoros",
            "Pedro Escobedo",
            "Peñamiller",
            "Pinal De Amoles",
            "Querétaro",
            "San Joaquín",
            "San Juan Del Río",
            "Tequisquiapan",
            "Tolimán"
        ],
    "Quintana Roo":[
            "Cozumel",
            "José María Morelos",
            "Felipe Carrillo Puerto",
            "Lázaro Cárdenas",
            "Isla Mujeres",
            "Solidaridad",
            "Othón P. Blanco",
            "Tulum",
            "Benito Juárez",
            "Bacalar"
        ],
    "San Luis Potosi":[
            "Ahualulco",
            "Alaquines",
            "Aquismón",
            "Armadillo De Los Infante",
            "Axtla De Terrazas",
            "Cárdenas",
            "Catorce",
            "Cedral",
            "Cerritos",
            "Cerro De San Pedro",
            "Charcas",
            "Ciudad Del Maíz",
            "Ciudad Fernández",
            "Ciudad Valles",
            "Coxcatlán",
            "Ebano",
            "El Naranjo",
            "Guadalcázar",
            "Huehuetlán",
            "Lagunillas",
            "Matehuala",
            "Matlapa",
            "Mexquitic De Carmona",
            "Moctezuma",
            "Rayón",
            "Rioverde",
            "Salinas",
            "San Antonio",
            "San Ciro De Acosta",
            "San Luis Potosí",
            "San Martín Chalchicuautla",
            "San Nicolás Tolentino",
            "San Vicente Tancuayalab",
            "Santa Catarina",
            "Santa María Del Río",
            "Santo Domingo",
            "Soledad De Graciano Sánchez",
            "Tamasopo",
            "Tamazunchale",
            "Tampacán",
            "Tampamolón Corona",
            "Tamuín",
            "Tancanhuitz",
            "Tanlajás",
            "Tanquián De Escobedo",
            "Tierra Nueva",
            "Vanegas",
            "Venado",
            "Villa De Arista",
            "Villa De Arriaga",
            "Villa De Guadalupe",
            "Villa De La Paz",
            "Villa De Ramos",
            "Villa De Reyes",
            "Villa Hidalgo",
            "Villa Juárez",
            "Xilitla",
            "Zaragoza"
        ],
    "Sinaloa":[
            "Ahome",
            "Angostura",
            "Badiraguato",
            "Choix",
            "Concordia",
            "Cosalá",
            "Culiacán",
            "El Fuerte",
            "Elota",
            "Escuinapa",
            "Guasave",
            "Mazatlán",
            "Mocorito",
            "Navolato",
            "Rosario",
            "Salvador Alvarado",
            "San Ignacio",
            "Sinaloa"
        ],
    "Sonora":[
            "Aconchi",
            "Agua Prieta",
            "Alamos",
            "Altar",
            "Arivechi",
            "Arizpe",
            "Atil",
            "Bacadéhuachi",
            "Bacanora",
            "Bacerac",
            "Bacoachi",
            "Bácum",
            "Banámichi",
            "Baviácora",
            "Bavispe",
            "Benito Juárez",
            "Benjamín Hill",
            "Caborca",
            "Cajeme",
            "Cananea",
            "Carbó",
            "Cucurpe",
            "Cumpas",
            "Divisaderos",
            "Empalme",
            "Etchojoa",
            "Fronteras",
            "General Plutarco Elías Calles",
            "Granados",
            "Guaymas",
            "Hermosillo",
            "Heroica Nogales",
            "Huachinera",
            "Huásabas",
            "Huatabampo",
            "Huépac",
            "Imuris",
            "La Colorada",
            "Magdalena",
            "Mazatán",
            "Moctezuma",
            "Naco",
            "Nácori Chico",
            "Nacozari De García",
            "Navojoa",
            "Onavas",
            "Opodepe",
            "Oquitoa",
            "Pitiquito",
            "Puerto Peñasco",
            "Quiriego",
            "Rayón",
            "Rosario",
            "Sahuaripa",
            "San Felipe De Jesús",
            "San Ignacio Río Muerto",
            "San Javier",
            "San Luis Río Colorado",
            "San Miguel De Horcasitas",
            "San Pedro De La Cueva",
            "Santa Ana",
            "Santa Cruz",
            "Sáric",
            "Soyopa",
            "Suaqui Grande",
            "Tepache",
            "Trincheras",
            "Tubutama",
            "Ures",
            "Villa Hidalgo",
            "Villa Pesqueira",
            "Yécora"
        ],
    "Tabasco":[
            "Balancán",
            "Cárdenas",
            "Centla",
            "Centro",
            "Comalcalco",
            "Cunduacán",
            "Emiliano Zapata",
            "Huimanguillo",
            "Jalapa",
            "Jalpa De Méndez",
            "Jonuta",
            "Macuspana",
            "Nacajuca",
            "Paraíso",
            "Tacotalpa",
            "Teapa",
            "Tenosique"
        ],
    "Tamaulipas":[
            "Abasolo",
            "Aldama",
            "Altamira",
            "Antiguo Morelos",
            "Burgos",
            "Bustamante",
            "Camargo",
            "Casas",
            "Ciudad Madero",
            "Cruillas",
            "El Mante",
            "G?Émez",
            "Gómez Farías",
            "González",
            "Guerrero",
            "Gustavo Díaz Ordaz",
            "Hidalgo",
            "Jaumave",
            "Jiménez",
            "Llera",
            "Mainero",
            "Matamoros",
            "Méndez",
            "Mier",
            "Miguel Alemán",
            "Miquihuana",
            "Nuevo Laredo",
            "Nuevo Morelos",
            "Ocampo",
            "Padilla",
            "Palmillas",
            "Reynosa",
            "Río Bravo",
            "San Carlos",
            "San Fernando",
            "San Nicolás",
            "Soto La Marina",
            "Tampico",
            "Tula",
            "Valle Hermoso",
            "Victoria",
            "Villagrán",
            "Xicoténcatl"
        ],
    "Tlaxcala":[
            "Acuamanala De Miguel Hidalgo",
            "Altzayanca",
            "Amaxac De Guerrero",
            "Apetatitlán De Antonio Carvajal",
            "Apizaco",
            "Atlangatepec",
            "Benito Juárez",
            "Calpulalpan",
            "Chiautempan",
            "Contla De Juan Cuamatzi",
            "Cuapiaxtla",
            "Cuaxomulco",
            "El Carmen Tequexquitla",
            "Emiliano Zapata",
            "Españita",
            "Huamantla",
            "Hueyotlipan",
            "Ixtacuixtla De Mariano Matamoros",
            "Ixtenco",
            "La Magdalena Tlaltelulco",
            "Lázaro Cárdenas",
            "Mazatecochco De José María Morelos",
            "Muñoz De Domingo Arenas",
            "Nanacamilpa De Mariano Arista",
            "Natívitas",
            "Panotla",
            "Papalotla De Xicohténcatl",
            "San Damián Texoloc",
            "San Francisco Tetlanohcan",
            "San Jerónimo Zacualpan",
            "San José Teacalco",
            "San Juan Huactzinco",
            "San Lorenzo Axocomanitla",
            "San Lucas Tecopilco",
            "San Pablo Del Monte",
            "Sanctórum De Lázaro Cárdenas",
            "Santa Ana Nopalucan",
            "Santa Apolonia Teacalco",
            "Santa Catarina Ayometla",
            "Santa Cruz Quilehtla",
            "Santa Cruz Tlaxcala",
            "Santa Isabel Xiloxoxtla",
            "Tenancingo",
            "Teolocholco",
            "Tepetitla De Lardizábal",
            "Tepeyanco",
            "Terrenate",
            "Tetla De La Solidaridad",
            "Tetlatlahuca",
            "Tlaxcala",
            "Tlaxco",
            "Tocatlán",
            "Totolac",
            "Tzompantepec",
            "Xaloztoc",
            "Xaltocan",
            "Xicohtzinco",
            "Yauhquemecan",
            "Zacatelco",
            "Zitlaltepec De Trinidad Sánchez Santos"
        ],
    "Veracruz":[
            "Acajete",
            "Acatlán",
            "Acayucan",
            "Actopan",
            "Acula",
            "Acultzingo",
            "Agua Dulce",
            "Alpatláhuac",
            "Alto Lucero De Gutiérrez Barrios",
            "Altotonga",
            "Alvarado",
            "Amatitlán",
            "Amatlán De Los Reyes",
            "Angel R. Cabada",
            "Apazapan",
            "Aquila",
            "Astacinga",
            "Atlahuilco",
            "Atoyac",
            "Atzacan",
            "Atzalan",
            "Ayahualulco",
            "Banderilla",
            "Benito Juárez",
            "Boca Del Río",
            "Calcahualco",
            "Camarón De Tejeda",
            "Camerino Z. Mendoza",
            "Carlos A. Carrillo",
            "Carrillo Puerto",
            "Castillo De Teayo",
            "Catemaco",
            "Cazones",
            "Cerro Azul",
            "Chacaltianguis",
            "Chalma",
            "Chiconamel",
            "Chiconquiaco",
            "Chicontepec",
            "Chinameca",
            "Chinampa De Gorostiza",
            "Chocamán",
            "Chontla",
            "Chumatlán",
            "Citlaltépetl",
            "Coacoatzintla",
            "Coahuitlán",
            "Coatepec",
            "Coatzacoalcos",
            "Coatzintla",
            "Coetzala",
            "Colipa",
            "Comapa",
            "Córdoba",
            "Cosamaloapan De Carpio",
            "Cosautlán De Carvajal",
            "Coscomatepec",
            "Cosoleacaque",
            "Cotaxtla",
            "Coxquihui",
            "Coyutla",
            "Cuichapa",
            "Cuitláhuac",
            "El Higo",
            "Emiliano Zapata",
            "Espinal",
            "Filomeno Mata",
            "Fortín",
            "Gutiérrez Zamora",
            "Hidalgotitlán",
            "Huatusco",
            "Huayacocotla",
            "Hueyapan De Ocampo",
            "Huiloapan",
            "Ignacio De La Llave",
            "Ilamatlán",
            "Isla",
            "Ixcatepec",
            "Ixhuacán De Los Reyes",
            "Ixhuatlán De Madero",
            "Ixhuatlán Del Café",
            "Ixhuatlán Del Sureste",
            "Ixhuatlancillo",
            "Ixmatlahuacan",
            "Ixtaczoquitlán",
            "Jalacingo",
            "Jalcomulco",
            "Jáltipan",
            "Jamapa",
            "Jesús Carranza",
            "Jilotepec",
            "José Azueta",
            "Juan Rodríguez Clara",
            "Juchique De Ferrer",
            "La Antigua",
            "La Perla",
            "Landero Y Coss",
            "Las Choapas",
            "Las Minas",
            "Las Vigas De Ramírez",
            "Lerdo De Tejada",
            "Los Reyes",
            "Magdalena",
            "Maltrata",
            "Manlio Fabio Altamirano",
            "Mariano Escobedo",
            "Martínez De La Torre",
            "Mecatlán",
            "Mecayapan",
            "Medellín",
            "Miahuatlán",
            "Minatitlán",
            "Misantla",
            "Mixtla De Altamirano",
            "Moloacán",
            "Nanchital De Lázaro Cárdenas Del R",
            "Naolinco",
            "Naranjal",
            "Naranjos Amatlán",
            "Nautla",
            "Nogales",
            "Oluta",
            "Omealca",
            "Orizaba",
            "Otatitlán",
            "Oteapan",
            "Ozuluama De Mascareñas",
            "Pajapan",
            "Pánuco",
            "Papantla",
            "Paso De Ovejas",
            "Paso Del Macho",
            "Perote",
            "Platón Sánchez",
            "Playa Vicente",
            "Poza Rica De Hidalgo",
            "Pueblo Viejo",
            "Puente Nacional",
            "Rafael Delgado",
            "Rafael Lucio",
            "Río Blanco",
            "Saltabarranca",
            "San Andrés Tenejapan",
            "San Andrés Tuxtla",
            "San Juan Evangelista",
            "San Rafael",
            "Santiago Sochiapan",
            "Santiago Tuxtla",
            "Sayula De Alemán",
            "Sochiapa",
            "Soconusco",
            "Soledad Atzompa",
            "Soledad De Doblado",
            "Soteapan",
            "Tamalín",
            "Tamiahua",
            "Tampico Alto",
            "Tancoco",
            "Tantima",
            "Tantoyuca",
            "Tatahuicapan De Juárez",
            "Tatatila",
            "Tecolutla",
            "Tehuipango",
            "Temapache",
            "Tempoal",
            "Tenampa",
            "Tenochtitlán",
            "Teocelo",
            "Tepatlaxco",
            "Tepetlán",
            "Tepetzintla",
            "Tequila",
            "Texcatepec",
            "Texhuacán",
            "Texistepec",
            "Tezonapa",
            "Tierra Blanca",
            "Tihuatlán",
            "Tlachichilco",
            "Tlacojalpan",
            "Tlacolulan",
            "Tlacotalpan",
            "Tlacotepec De Mejía",
            "Tlalixcoyan",
            "Tlalnelhuayocan",
            "Tlaltetela",
            "Tlapacoyan",
            "Tlaquilpa",
            "Tlilapan",
            "Tomatlán",
            "Tonayán",
            "Totutla",
            "Tres Valles",
            "Túxpam",
            "Tuxtilla",
            "Ursulo Galván",
            "Uxpanapa",
            "Vega De Alatorre",
            "Veracruz",
            "Villa Aldama",
            "Xalapa",
            "Xico",
            "Xoxocotla",
            "Yanga",
            "Yecuatla",
            "Zacualpan",
            "Zaragoza",
            "Zentla",
            "Zongolica",
            "Zontecomatlán De López Y Fuentes",
            "Zozocolco De Hidalgo"
        ],
    "Yucatan":[
            "Abalá",
            "Acanceh",
            "Akil",
            "Baca",
            "Bokobá",
            "Buctzotz",
            "Cacalchén",
            "Calotmul",
            "Cansahcab",
            "Cantamayec",
            "Celestún",
            "Cenotillo",
            "Chacsinkín",
            "Chankom",
            "Chapab",
            "Chemax",
            "Chichimilá",
            "Chicxulub Pueblo",
            "Chikindzonot",
            "Chocholá",
            "Chumayel",
            "Conkal",
            "Cuncunul",
            "Cuzamá",
            "Dzán",
            "Dzemul",
            "Dzidzantún",
            "Dzilam De Bravo",
            "Dzilam González",
            "Dzitás",
            "Dzoncauich",
            "Espita",
            "Halachó",
            "Hocabá",
            "Hoctún",
            "Homún",
            "Huhí",
            "Hunucmá",
            "Ixil",
            "Izamal",
            "Kanasín",
            "Kantunil",
            "Kaua",
            "Kinchil",
            "Kopomá",
            "Mama",
            "Maní",
            "Maxcanú",
            "Mayapán",
            "Mérida",
            "Mocochá",
            "Motul",
            "Muna",
            "Muxupip",
            "Opichén",
            "Oxkutzcab",
            "Panabá",
            "Peto",
            "Progreso",
            "Quintana Roo",
            "Río Lagartos",
            "Sacalum",
            "Samahil",
            "San Felipe",
            "Sanahcat",
            "Santa Elena",
            "Seyé",
            "Sinanché",
            "Sotuta",
            "Sucilá",
            "Sudzal",
            "Suma",
            "Tahdziú",
            "Tahmek",
            "Teabo",
            "Tecoh",
            "Tekal De Venegas",
            "Tekantó",
            "Tekax",
            "Tekit",
            "Tekom",
            "Telchac Pueblo",
            "Telchac Puerto",
            "Temax",
            "Temozón",
            "Tepakán",
            "Tetiz",
            "Teya",
            "Ticul",
            "Timucuy",
            "Tinum",
            "Tixcacalcupul",
            "Tixkokob",
            "Tixmehuac",
            "Tixpéhual",
            "Tizimín",
            "Tunkás",
            "Tzucacab",
            "Uayma",
            "Ucú",
            "Umán",
            "Valladolid",
            "Xocchel",
            "Yaxcabá",
            "Yaxkukul",
            "Yobaín"
        ],
    "Zacatecas":[
            "Apozol",
            "Apulco",
            "Atolinga",
            "Benito Juárez",
            "Calera",
            "Cañitas De Felipe Pescador",
            "Chalchihuites",
            "Concepción Del Oro",
            "Cuauhtémoc",
            "El Plateado De Joaquín Amaro",
            "El Salvador",
            "Fresnillo",
            "Genaro Codina",
            "General Enrique Estrada",
            "General Francisco R. Murguía",
            "General Pánfilo Natera",
            "Guadalupe",
            "Huanusco",
            "Jalpa",
            "Jerez",
            "Jiménez Del Teul",
            "Juan Aldama",
            "Juchipila",
            "Loreto",
            "Luis Moya",
            "Mazapil",
            "Melchor Ocampo",
            "Mezquital Del Oro",
            "Miguel Auza",
            "Momax",
            "Monte Escobedo",
            "Morelos",
            "Moyahua De Estrada",
            "Nochistlán De Mejía",
            "Noria De ?Ngeles",
            "Ojocaliente",
            "Pánuco",
            "Pinos",
            "Río Grande",
            "Sain Alto",
            "Santa María De La Paz",
            "Sombrerete",
            "Susticacán",
            "Tabasco",
            "Tepechitlán",
            "Tepetongo",
            "Teul De González Ortega",
            "Tlaltenango De Sánchez Román",
            "Trancoso",
            "Trinidad García De La Cadena",
            "Valparaíso",
            "Vetagrande",
            "Villa De Cos",
            "Villa García",
            "Villa González Ortega",
            "Villa Hidalgo",
            "Villanueva",
            "Zacatecas"
        ],
}
